spring.application.name=Backend
spring.profiles.default=local
app.cors.allowed-origins=http://localhost:4200,http://127.0.0.1:4200,http://host.docker.internal:4200
server.port=8081
# Actuator / Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

#Para el swagger
springdoc.enable-hateoas=false
springdoc.enable-data-rest=false